# Generated by Django 4.2.5 on 2024-03-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_train', '0004_alter_author_options_alter_authorprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('tags', models.ManyToManyField(related_name='entries', to='db_train.tag')),
            ],
        ),
    ]
